[GH-2] Support for RPM based installation
chef-cookbooks/chef-grafana pull request #3
Opened 2016-10-01 15:28 UTC by daharon

### Description

Support for Red Hat based distributions.

### Issues Resolved

GH-2

### Check List
- [X] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [ ] New functionality includes testing.
- [X] New functionality has been documented in the README if applicable
- [ ] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

2016-10-18 06:20 UTC, daharon commented
@tas50 Can you please take a look?

2017-01-10 14:17 UTC, ernestas-poskus commented
@tas50 @mivok @tmonk42 

what is the status of this

2017-03-30 04:43 UTC, iennae commented on recipes/install.rb
> +    baseurl 'https://packagecloud.io/grafana/stable/el/$releasever/$basearch'
$releasever requires centos-release package. In the yum cookbooks we've been updating to use #{node['platform_version'].to_i} instead.

2017-03-30 04:47 UTC, iennae requested changes
Can you rebase to master and update the use of $releasever? Thanks so much for this contribution.

2017-04-02 00:42 UTC, iennae approved these changes

2017-04-02 00:42 UTC, merged

2017-04-02 00:42 UTC, iennae commented
Thanks so much for the contribution!

2017-04-05 06:01 UTC, fletchowns commented
Thank you @daharon !